<template>
    <div class="mod-config">
        <el-table-column
                type="selection"
                header-align="center"
                align="center"
                width="50">
        </el-table-column>
        <el-table-column
                prop="purchaseId"
                header-align="center"
                align="center"
                label="单号">
        </el-table-column>
        <el-table-column
                prop="supplierName"
                header-align="center"
                align="center"
                label="供应商">
        </el-table-column>
        <el-table-column
                prop="purchaseAmountPayable"
                header-align="center"
                align="center"
                label="购入应付金额">
        </el-table-column>
        <el-table-column
                prop="purchaseActualAmountPaid"
                header-align="center"
                align="center"
                label="购入实付金额">
        </el-table-column>
        <el-table-column
                prop="purchaseTime"
                header-align="center"
                align="center"
                label="购入日期"
                width="190">
        </el-table-column>
    </div>
</template>
